import type { ResourcePack, MinecraftVersion } from '../models/ResourcePack';

/**
 * Mock data for development
 * This simulates the data that will come from the backend API
 */

export const mockMinecraftVersions: MinecraftVersion[] = [
    { id: '1', version: '1.20.1', releaseDate: new Date('2023-06-12') },
    { id: '2', version: '1.19.4', releaseDate: new Date('2023-03-14') },
    { id: '3', version: '1.19.2', releaseDate: new Date('2022-08-05') },
    { id: '4', version: '1.18.2', releaseDate: new Date('2022-02-28') },
    { id: '5', version: '1.16.5', releaseDate: new Date('2021-01-15') },
];

export const mockResourcePacks: ResourcePack[] = [
    {
        id: '1',
        name: 'Faithful 32x',
        description: 'A double resolution texture pack that stays faithful to the original Minecraft textures',
        author: 'Faithful Team',
        tags: ['vanilla', 'faithful', 'HD'],
        thumbnailUrl: 'https://via.placeholder.com/300x200/2e7d32/ffffff?text=Faithful+32x',
        downloadUrl: '/downloads/faithful-32x.zip',
        fileSize: 15728640, // 15 MB
        uploadDate: new Date('2024-01-15'),
        lastModified: new Date('2024-10-20'),
        minecraftVersions: [
            mockMinecraftVersions[0],
            mockMinecraftVersions[1],
        ],
        supportedMods: [
            { id: 'm1', name: 'OptiFine', version: '1.20.1' },
        ],
        supportedModpacks: [],
        downloadCount: 15432,
        isArchived: false,
    },
    {
        id: '2',
        name: 'Mizuno\'s 16 Craft',
        description: 'CIT resource pack with detailed textures for a more realistic Minecraft experience',
        author: 'Mizuno',
        tags: ['realistic', 'CIT', 'detailed'],
        thumbnailUrl: 'https://via.placeholder.com/300x200/8d6e63/ffffff?text=Mizuno+16',
        downloadUrl: '/downloads/mizunos-16.zip',
        fileSize: 25165824, // 24 MB
        uploadDate: new Date('2024-02-10'),
        lastModified: new Date('2024-10-18'),
        minecraftVersions: [
            mockMinecraftVersions[0],
            mockMinecraftVersions[1],
            mockMinecraftVersions[2],
        ],
        supportedMods: [
            { id: 'm1', name: 'OptiFine', version: '1.20.1' },
            { id: 'm2', name: 'CIT Resewn', version: '1.1.3' },
        ],
        supportedModpacks: [
            { id: 'mp1', name: 'All the Mods 9', version: '0.2.44' },
        ],
        downloadCount: 8921,
        isArchived: false,
    },
    {
        id: '3',
        name: 'Vanilla Tweaks',
        description: 'Customize your Minecraft experience with subtle improvements and tweaks',
        author: 'Xisumavoid',
        tags: ['vanilla', 'quality-of-life', 'customizable'],
        thumbnailUrl: 'https://via.placeholder.com/300x200/60ad5e/ffffff?text=Vanilla+Tweaks',
        downloadUrl: '/downloads/vanilla-tweaks.zip',
        fileSize: 5242880, // 5 MB
        uploadDate: new Date('2024-03-05'),
        lastModified: new Date('2024-10-22'),
        minecraftVersions: [
            mockMinecraftVersions[0],
            mockMinecraftVersions[1],
            mockMinecraftVersions[2],
            mockMinecraftVersions[3],
        ],
        supportedMods: [],
        supportedModpacks: [],
        downloadCount: 23456,
        isArchived: false,
    },
    {
        id: '4',
        name: 'Create: Resource Pack',
        description: 'Official resource pack for the Create mod with custom textures and models',
        author: 'simibubi',
        tags: ['mod-specific', 'create', 'mechanical'],
        thumbnailUrl: 'https://via.placeholder.com/300x200/be9c91/ffffff?text=Create+Pack',
        downloadUrl: '/downloads/create-pack.zip',
        fileSize: 10485760, // 10 MB
        uploadDate: new Date('2024-04-12'),
        lastModified: new Date('2024-09-30'),
        minecraftVersions: [
            mockMinecraftVersions[0],
            mockMinecraftVersions[1],
        ],
        supportedMods: [
            { id: 'm3', name: 'Create', version: '0.5.1' },
        ],
        supportedModpacks: [
            { id: 'mp2', name: 'Create: Above and Beyond', version: '1.3' },
        ],
        downloadCount: 12098,
        isArchived: false,
    },
    {
        id: '5',
        name: 'Sphax PureBDcraft',
        description: 'Comic-style texture pack with vibrant colors and unique art style',
        author: 'Sphax',
        tags: ['comic', 'HD', 'colorful'],
        thumbnailUrl: 'https://via.placeholder.com/300x200/ff6f00/ffffff?text=Sphax',
        downloadUrl: '/downloads/sphax.zip',
        fileSize: 42991616, // 41 MB
        uploadDate: new Date('2024-01-20'),
        lastModified: new Date('2024-10-15'),
        minecraftVersions: [mockMinecraftVersions[0], mockMinecraftVersions[1], mockMinecraftVersions[2]],
        supportedMods: [{ id: 'm1', name: 'OptiFine', version: '1.20.1' }],
        supportedModpacks: [],
        downloadCount: 18765,
        isArchived: false,
    },
    {
        id: '6',
        name: 'John Smith Legacy',
        description: 'Medieval-themed texture pack with rustic and aged look',
        author: 'JohnSmith',
        tags: ['medieval', 'rustic', 'classic'],
        thumbnailUrl: 'https://via.placeholder.com/300x200/795548/ffffff?text=John+Smith',
        downloadUrl: '/downloads/johnsmith.zip',
        fileSize: 18874368, // 18 MB
        uploadDate: new Date('2024-02-14'),
        lastModified: new Date('2024-10-10'),
        minecraftVersions: [mockMinecraftVersions[0], mockMinecraftVersions[2], mockMinecraftVersions[3]],
        supportedMods: [],
        supportedModpacks: [],
        downloadCount: 9234,
        isArchived: false,
    },
    {
        id: '7',
        name: 'Flows HD',
        description: 'High definition pack with realistic water and improved particles',
        author: 'FlowsHD',
        tags: ['HD', 'realistic', 'water'],
        thumbnailUrl: 'https://via.placeholder.com/300x200/2196f3/ffffff?text=Flows+HD',
        downloadUrl: '/downloads/flows-hd.zip',
        fileSize: 31457280, // 30 MB
        uploadDate: new Date('2024-03-08'),
        lastModified: new Date('2024-10-19'),
        minecraftVersions: [mockMinecraftVersions[0], mockMinecraftVersions[1]],
        supportedMods: [{ id: 'm1', name: 'OptiFine', version: '1.20.1' }],
        supportedModpacks: [],
        downloadCount: 14521,
        isArchived: false,
    },
    {
        id: '8',
        name: 'Coterie Craft',
        description: 'RPG-style texture pack with fantasy elements',
        author: 'CoterieCraft Team',
        tags: ['RPG', 'fantasy', 'adventure'],
        thumbnailUrl: 'https://via.placeholder.com/300x200/9c27b0/ffffff?text=Coterie',
        downloadUrl: '/downloads/coterie.zip',
        fileSize: 22020096, // 21 MB
        uploadDate: new Date('2024-01-30'),
        lastModified: new Date('2024-09-25'),
        minecraftVersions: [mockMinecraftVersions[1], mockMinecraftVersions[2], mockMinecraftVersions[3]],
        supportedMods: [],
        supportedModpacks: [{ id: 'mp1', name: 'All the Mods 9', version: '0.2.44' }],
        downloadCount: 7654,
        isArchived: false,
    },
    {
        id: '9',
        name: 'Bare Bones',
        description: 'Minimalist texture pack that simplifies Minecraft visuals',
        author: 'RobotPantaloons',
        tags: ['minimalist', 'simple', 'performance'],
        thumbnailUrl: 'https://via.placeholder.com/300x200/607d8b/ffffff?text=Bare+Bones',
        downloadUrl: '/downloads/barebones.zip',
        fileSize: 3145728, // 3 MB
        uploadDate: new Date('2024-04-05'),
        lastModified: new Date('2024-10-21'),
        minecraftVersions: [mockMinecraftVersions[0], mockMinecraftVersions[1], mockMinecraftVersions[2], mockMinecraftVersions[3]],
        supportedMods: [],
        supportedModpacks: [],
        downloadCount: 19876,
        isArchived: false,
    },
    {
        id: '10',
        name: 'Soartex Fanver',
        description: 'Smooth and clean textures with a modern aesthetic',
        author: 'Soartex',
        tags: ['smooth', 'modern', 'clean'],
        thumbnailUrl: 'https://via.placeholder.com/300x200/4caf50/ffffff?text=Soartex',
        downloadUrl: '/downloads/soartex.zip',
        fileSize: 16777216, // 16 MB
        uploadDate: new Date('2024-02-28'),
        lastModified: new Date('2024-10-12'),
        minecraftVersions: [mockMinecraftVersions[0], mockMinecraftVersions[1], mockMinecraftVersions[2]],
        supportedMods: [{ id: 'm3', name: 'Create', version: '0.5.1' }],
        supportedModpacks: [],
        downloadCount: 11234,
        isArchived: false,
    },
    {
        id: '11',
        name: 'Dokucraft',
        description: 'Dark and atmospheric pack perfect for adventure maps',
        author: 'Doku',
        tags: ['dark', 'atmospheric', 'adventure'],
        thumbnailUrl: 'https://via.placeholder.com/300x200/37474f/ffffff?text=Dokucraft',
        downloadUrl: '/downloads/dokucraft.zip',
        fileSize: 20971520, // 20 MB
        uploadDate: new Date('2024-01-10'),
        lastModified: new Date('2024-09-18'),
        minecraftVersions: [mockMinecraftVersions[1], mockMinecraftVersions[2], mockMinecraftVersions[3], mockMinecraftVersions[4]],
        supportedMods: [],
        supportedModpacks: [],
        downloadCount: 8432,
        isArchived: false,
    },
    {
        id: '12',
        name: 'Umsoea',
        description: 'Vibrant and colorful pack with enhanced biomes',
        author: 'Umsoea',
        tags: ['colorful', 'biomes', 'vibrant'],
        thumbnailUrl: 'https://via.placeholder.com/300x200/e91e63/ffffff?text=Umsoea',
        downloadUrl: '/downloads/umsoea.zip',
        fileSize: 14680064, // 14 MB
        uploadDate: new Date('2024-03-22'),
        lastModified: new Date('2024-10-16'),
        minecraftVersions: [mockMinecraftVersions[0], mockMinecraftVersions[1]],
        supportedMods: [{ id: 'm1', name: 'OptiFine', version: '1.20.1' }],
        supportedModpacks: [],
        downloadCount: 13567,
        isArchived: false,
    },
    {
        id: '13',
        name: 'Conquest Reforged',
        description: 'Medieval building pack with thousands of new blocks',
        author: 'Conquest Team',
        tags: ['medieval', 'building', 'detailed'],
        thumbnailUrl: 'https://via.placeholder.com/300x200/8d6e63/ffffff?text=Conquest',
        downloadUrl: '/downloads/conquest.zip',
        fileSize: 52428800, // 50 MB
        uploadDate: new Date('2024-02-05'),
        lastModified: new Date('2024-10-08'),
        minecraftVersions: [mockMinecraftVersions[0], mockMinecraftVersions[1], mockMinecraftVersions[2]],
        supportedMods: [{ id: 'm2', name: 'CIT Resewn', version: '1.1.3' }],
        supportedModpacks: [],
        downloadCount: 16789,
        isArchived: false,
    },
    {
        id: '14',
        name: 'Fresh Animations',
        description: 'Adds smooth animations to mobs and players',
        author: 'FreshLX',
        tags: ['animations', 'mobs', 'smooth'],
        thumbnailUrl: 'https://via.placeholder.com/300x200/ff9800/ffffff?text=Fresh+Anim',
        downloadUrl: '/downloads/fresh-animations.zip',
        fileSize: 8388608, // 8 MB
        uploadDate: new Date('2024-04-18'),
        lastModified: new Date('2024-10-20'),
        minecraftVersions: [mockMinecraftVersions[0], mockMinecraftVersions[1], mockMinecraftVersions[2]],
        supportedMods: [{ id: 'm1', name: 'OptiFine', version: '1.20.1' }],
        supportedModpacks: [],
        downloadCount: 21345,
        isArchived: false,
    },
    {
        id: '15',
        name: 'Better Leaves Add-on',
        description: 'Makes leaves bushy and full without performance impact',
        author: 'XLuma',
        tags: ['leaves', 'nature', 'add-on'],
        thumbnailUrl: 'https://via.placeholder.com/300x200/4caf50/ffffff?text=Better+Leaves',
        downloadUrl: '/downloads/better-leaves.zip',
        fileSize: 2097152, // 2 MB
        uploadDate: new Date('2024-03-15'),
        lastModified: new Date('2024-10-17'),
        minecraftVersions: [mockMinecraftVersions[0], mockMinecraftVersions[1], mockMinecraftVersions[2], mockMinecraftVersions[3]],
        supportedMods: [],
        supportedModpacks: [],
        downloadCount: 17890,
        isArchived: false,
    },
    {
        id: '16',
        name: 'Dramatic Skys',
        description: 'Beautiful sky textures with dynamic clouds',
        author: 'DragonGaming',
        tags: ['sky', 'clouds', 'atmospheric'],
        thumbnailUrl: 'https://via.placeholder.com/300x200/03a9f4/ffffff?text=Dramatic+Skys',
        downloadUrl: '/downloads/dramatic-skys.zip',
        fileSize: 6291456, // 6 MB
        uploadDate: new Date('2024-01-25'),
        lastModified: new Date('2024-09-28'),
        minecraftVersions: [mockMinecraftVersions[0], mockMinecraftVersions[1]],
        supportedMods: [{ id: 'm1', name: 'OptiFine', version: '1.20.1' }],
        supportedModpacks: [],
        downloadCount: 10234,
        isArchived: false,
    },
    {
        id: '17',
        name: 'Complementary Shaders',
        description: 'Shader-like effects without requiring actual shaders',
        author: 'EminGT',
        tags: ['shaders', 'lighting', 'effects'],
        thumbnailUrl: 'https://via.placeholder.com/300x200/ffc107/ffffff?text=Complementary',
        downloadUrl: '/downloads/complementary.zip',
        fileSize: 12582912, // 12 MB
        uploadDate: new Date('2024-04-01'),
        lastModified: new Date('2024-10-22'),
        minecraftVersions: [mockMinecraftVersions[0], mockMinecraftVersions[1], mockMinecraftVersions[2]],
        supportedMods: [{ id: 'm1', name: 'OptiFine', version: '1.20.1' }],
        supportedModpacks: [],
        downloadCount: 25678,
        isArchived: false,
    },
    {
        id: '18',
        name: 'Jolicraft',
        description: 'Cute and colorful cartoon-style textures',
        author: 'Jolicraft',
        tags: ['cartoon', 'cute', 'colorful'],
        thumbnailUrl: 'https://via.placeholder.com/300x200/e91e63/ffffff?text=Jolicraft',
        downloadUrl: '/downloads/jolicraft.zip',
        fileSize: 17825792, // 17 MB
        uploadDate: new Date('2024-02-20'),
        lastModified: new Date('2024-10-11'),
        minecraftVersions: [mockMinecraftVersions[1], mockMinecraftVersions[2], mockMinecraftVersions[3]],
        supportedMods: [],
        supportedModpacks: [],
        downloadCount: 9876,
        isArchived: false,
    },
    {
        id: '19',
        name: 'Compliance 64x',
        description: 'Quadruple resolution faithful textures',
        author: 'Compliance Team',
        tags: ['faithful', 'HD', 'high-res'],
        thumbnailUrl: 'https://via.placeholder.com/300x200/2e7d32/ffffff?text=Compliance+64x',
        downloadUrl: '/downloads/compliance-64x.zip',
        fileSize: 36700160, // 35 MB
        uploadDate: new Date('2024-03-12'),
        lastModified: new Date('2024-10-19'),
        minecraftVersions: [mockMinecraftVersions[0], mockMinecraftVersions[1]],
        supportedMods: [{ id: 'm1', name: 'OptiFine', version: '1.20.1' }],
        supportedModpacks: [],
        downloadCount: 14321,
        isArchived: false,
    },
    {
        id: '20',
        name: 'Chromahills',
        description: 'Vibrant RPG pack with custom models',
        author: 'Chromahills',
        tags: ['RPG', 'models', 'vibrant'],
        thumbnailUrl: 'https://via.placeholder.com/300x200/9c27b0/ffffff?text=Chromahills',
        downloadUrl: '/downloads/chromahills.zip',
        fileSize: 28311552, // 27 MB
        uploadDate: new Date('2024-01-18'),
        lastModified: new Date('2024-09-22'),
        minecraftVersions: [mockMinecraftVersions[0], mockMinecraftVersions[1], mockMinecraftVersions[2]],
        supportedMods: [{ id: 'm2', name: 'CIT Resewn', version: '1.1.3' }],
        supportedModpacks: [{ id: 'mp1', name: 'All the Mods 9', version: '0.2.44' }],
        downloadCount: 11567,
        isArchived: false,
    },
    {
        id: '21',
        name: 'Sapixcraft',
        description: 'Smooth semi-realistic textures with soft colors',
        author: 'Sapix',
        tags: ['smooth', 'realistic', 'soft'],
        thumbnailUrl: 'https://via.placeholder.com/300x200/795548/ffffff?text=Sapixcraft',
        downloadUrl: '/downloads/sapixcraft.zip',
        fileSize: 19922944, // 19 MB
        uploadDate: new Date('2024-04-10'),
        lastModified: new Date('2024-10-14'),
        minecraftVersions: [mockMinecraftVersions[0], mockMinecraftVersions[2], mockMinecraftVersions[3]],
        supportedMods: [],
        supportedModpacks: [],
        downloadCount: 8765,
        isArchived: false,
    },
    {
        id: '22',
        name: 'Xenocontendi',
        description: 'Modern minimalist pack with clean lines',
        author: 'Xeno',
        tags: ['modern', 'minimalist', 'clean'],
        thumbnailUrl: 'https://via.placeholder.com/300x200/607d8b/ffffff?text=Xenocontendi',
        downloadUrl: '/downloads/xenocontendi.zip',
        fileSize: 13631488, // 13 MB
        uploadDate: new Date('2024-02-16'),
        lastModified: new Date('2024-10-09'),
        minecraftVersions: [mockMinecraftVersions[0], mockMinecraftVersions[1], mockMinecraftVersions[2]],
        supportedMods: [],
        supportedModpacks: [],
        downloadCount: 12456,
        isArchived: false,
    },
    {
        id: '23',
        name: 'Halo\'s Tweaks',
        description: 'Subtle improvements to vanilla textures',
        author: 'HaloWolf',
        tags: ['vanilla', 'tweaks', 'subtle'],
        thumbnailUrl: 'https://via.placeholder.com/300x200/60ad5e/ffffff?text=Halo+Tweaks',
        downloadUrl: '/downloads/halos-tweaks.zip',
        fileSize: 7340032, // 7 MB
        uploadDate: new Date('2024-03-28'),
        lastModified: new Date('2024-10-20'),
        minecraftVersions: [mockMinecraftVersions[0], mockMinecraftVersions[1], mockMinecraftVersions[2], mockMinecraftVersions[3]],
        supportedMods: [],
        supportedModpacks: [],
        downloadCount: 16543,
        isArchived: false,
    },
    {
        id: '24',
        name: 'Nate\'s Tweaks',
        description: 'Quality of life texture improvements',
        author: 'NateJeff',
        tags: ['quality-of-life', 'improvements', 'vanilla'],
        thumbnailUrl: 'https://via.placeholder.com/300x200/ff6f00/ffffff?text=Nate+Tweaks',
        downloadUrl: '/downloads/nates-tweaks.zip',
        fileSize: 5767168, // 5.5 MB
        uploadDate: new Date('2024-04-22'),
        lastModified: new Date('2024-10-21'),
        minecraftVersions: [mockMinecraftVersions[0], mockMinecraftVersions[1]],
        supportedMods: [{ id: 'm1', name: 'OptiFine', version: '1.20.1' }],
        supportedModpacks: [],
        downloadCount: 19234,
        isArchived: false,
    },
];
