name: Update Jira on PR merge
on:
  pull_request:
    types: [closed]

jobs:
  update-jira:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Extract Jira issue key from PR title or branch
        shell: bash
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          if [[ "$TITLE" =~ ([A-Z][A-Z0-9]+-[0-9]+) ]]; then
            echo "ISSUE=${BASH_REMATCH[1]}" >> $GITHUB_ENV
          else
            BRANCH="${{ github.event.pull_request.head.ref }}"
            if [[ "$BRANCH" =~ ([A-Z][A-Z0-9]+-[0-9]+) ]]; then
              echo "ISSUE=${BASH_REMATCH[1]}" >> $GITHUB_ENV
            else
              echo "No Jira issue key found in PR title or branch name; exiting"
              exit 0
            fi
          fi

      - name: Add comment to Jira
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
        run: |
          curl -s -u "$JIRA_USER:$JIRA_TOKEN" -X POST -H "Content-Type: application/json" \
            "$JIRA_BASE_URL/rest/api/3/issue/$ISSUE/comment" \
            -d "{\"body\":\"PR #${{ github.event.pull_request.number }} merged in ${GITHUB_REPOSITORY}\"}"

      - name: Set due date +3 days (example)
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
        run: |
          # Linux date; fallback for macOS runners
          if date -d "+3 days" >/dev/null 2>&1; then
            DUEDATE=$(date -d "+3 days" +%F)
          else
            DUEDATE=$(date -v+3d +%F)
          fi
          curl -s -u "$JIRA_USER:$JIRA_TOKEN" -X PUT -H "Content-Type: application/json" \
            "$JIRA_BASE_URL/rest/api/3/issue/$ISSUE" \
            -d "{\"fields\":{\"duedate\":\"$DUEDATE\"}}"